include $(TOPDIR)/rules.mk

LUCI2_TITLE:=SQM Scripts - LuCI2 interface
LUCI2_DEPENDS:=+luci2-base +sqm-scripts +rpcd-mod-file
LUCI2_DESCRIPTION:=Control the simple_qos SQM script

include ../../luci2.mk

# call BuildPackage - OpenWrt buildroot signature